tryuri:
  - path: /
    script: /index.php

ossprefix:
  - /ace/app/

error_page:
    - status: 504 505
      page: /50x.html

# 这里对应的 nginx 规则为: rewrite ^/1.jpg$ /hello.php last;
rewrite:
- url: ^/zhihu/zhuanlan/(.*)$
  script: /zhihu-zhuanlan/index.php?name=$1
  checkfile: false
