rewrite:
  - url: ^/zhihu/zhuanlan/(.*)$
    script: /zhihu-zhuanlan/index.php?name=$1
    checkfile: false

tryuri:
  - path: /
    script: /index.php

ossprefix:
  - /ace/app/

error_page:
  - status: 504 505
    page: /50x.html

